package com.parita.jetpackcomposeapp.util

object JetpackConstant {
    const val GM = "Good Morning"
    const val GA = "Good Afternoon"
    const val GE = "Good Evening"
    const val GN = "Good Night"
    const val NA = "No Data"
    const val SleepMeditation = "Sleep meditation"
    const val TipsForSleeping = "Tips for sleeping"
    const val NightIsland = "Night island"
    const val CalmingSound = "Calming sounds"
    const val BASE_URL = "https://shazam.p.rapidapi.com"
    const val RapidApi_Key_Name = "X-RapidAPI-Key"
    const val RapidAPI_KEY = "b741a1115cmsh2000882239b456ep1fe83ajsn1ce716699ab9"
    const val RapidApi_host_Name = "X-RapidAPI-Host"
    const val RapidAPI_Host = "shazam.p.rapidapi.com"
    const val NLS = "NoteListScreen"
    const val ANS1 = "AddNoteScreen_1"
    const val ANS2 = "AddNoteScreen_2"
    const val RNS = "ReadNoteScreen"
    const val description = "description"
    const val title = "title"
    const val NDF = "No data found"
    const val UNS = "UpdateNoteScreen"
}